site_name: Tojo-san Docs
site_url: https://fokastudio.github.io/Kirumi-Tojo/
site_author: FokaStudio
site_description: >-
  Documentation and Website for Kirumi Tojo Discord bot
nav:
    - Home: index.md
    - Tasklist: tasklist.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/J6guYAySN8
      name: Kirumi Tojo Support Server
    - icon: fontawesome/brands/patreon
      link: https://patreon.com/FokaStudio
      name: Kirumi Tojo Support Server
    - icon: fontawesome/brands/paypal
      link: https://paypal.me/FokaStudio
      name: Kirumi Tojo Support Server

repo_url: https://github.com/FokaStudio/Kirumi-Tojo
repo_name: Tojo-san on Github

markdown_extensions:
  - extra
  - admonition
  - attr_list
  - md_in_html
  - meta
  - abbr
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  
  - toc:
      permalink: "#"

copyright: Copyright &copy; 2021 - 2021 Filip 'FokaStudio' Raczkowski

extra:
  generator: false

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: datetime
      fallback_to_build_date: true
      enable_creation_date: true
  - minify:
      minify_html: true

theme:
  name: material
  
  include_search_page: false
  search_index_only: true
  
  font:
    text: Saira 

  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - content.tabs.link
    - toc.integrate

  palette:
    scheme: slate
    primary: grey
    accent: blue
  
  favicon: docs/assets/icon.png
  logo: docs/assets/icon.png

  icon:
    repo: fontawesome/solid/trash
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
